version: 2.1
jobs:
  build:
    docker: 
      - image: innovanon/poobuntu:latest
    parallelism: 4
    steps:
      - checkout # check out the code in the project directory
      - 
      - run:
          name:    Making the Project
          #command: make -j`nproc`
          command: make -j2
      - run:
          name:    Cleanup
          #command: make -j`nproc` clean
          command: make -j2 clean
      - store_artifacts:
          path: logo.png
      - store_artifacts:
          path: logo-visible.png
      - store_artifacts:
          path: logo-midvisible.png
      - store_artifacts:
          path: logo-animated.gif
      - store_artifacts:
          path: logo-small-animated.gif
      - store_artifacts:
          path: apple-touch-icon-120x120.png
      - store_artifacts:
          path: apple-touch-icon-152x152.png
      - store_artifacts:
          path: apple-touch-icon-60x60.png
      - store_artifacts:
          path: apple-touch-icon-76x76.png
      - store_artifacts:
          path: syslinux-splash.bmp
      - store_artifacts:
          path: grub-splash.xpm.gz
      - store_artifacts:
          path: favicon.ico
      - store_artifacts:
          path: github.png
      - store_artifacts:
          path: twitter-banner.png
      - store_artifacts:
          path: linkedin-banner.png
      - store_artifacts:
          path: youtube-banner.png
      - store_artifacts:
          path: soundcloud-banner.png

